---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-v2-4-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-v2-4
spec:
  type: ClusterIP
  ports:
    - port: 12000
      protocol: UDP
      targetPort: 12000
      name: port-12000
    - port: 13000
      protocol: TCP
      targetPort: 13000
      name: port-13000
  selector:
    app: ssv-node-v2-4
---
apiVersion: REPLACE_API_VERSION 
kind: Deployment
metadata:
  labels:
    app: ssv-node-v2-4
  name: ssv-node-v2-4
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-v2-4
  template:
    metadata:
      labels:
        app: ssv-node-v2-4
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - ssv-node-v2-1
              topologyKey: kubernetes.io/hostname
            weight: 1
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - ssv-node-v2-2
              topologyKey: kubernetes.io/hostname
            weight: 1
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - ssv-node-v2-3
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - name: ssv-node-v2-4
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG 
        imagePullPolicy: Always
        command: ["make", "start-node"]
        ports:
        - containerPort: 12000
          name: port-12000
          protocol: UDP
          hostPort: 12000            
        - containerPort: 13000
          name: port-13000
          hostPort: 13000
        env:
        - name: SHARE_CONFIG
          value: "./data/share.yaml"
        - name: NODE_ID
          value: "4"
        - name: SSV_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: ssv_node_v2_4
        - name: VALIDATOR_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: validator_public_key_v2
        - name: BEACON_NODE_ADDR
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: beacon_node_addr
        - name: PUBKEY_NODE_1
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: pubkey_node_v2_1
        - name: PUBKEY_NODE_2
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: pubkey_node_v2_2
        - name: PUBKEY_NODE_3
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: pubkey_node_v2_3
        - name: ETH_1_ADDR
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: eth1_addr
        - name: CONFIG_PATH
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: config_path
        - name: ENR_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: enr_key
        - name: SMART_CONTRACT_ADDR_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: smart_contract_addr_key
        - name: LOG_LEVEL
          value: "debug"
        - name: DISCOVERY_TYPE_KEY
          value: "discv5"
        - name: NETWORK
          value: "pyrmont" 
        - name: CONSENSUS_TYPE
          value: "validation"
        - name: HOST_DNS
          value: ""
        - name: HOST_ADDRESS
          value: ""
        - name: GENESIS_EPOCH
          value: "34165"
        - name: LOGGER_LEVEL
          value: "debug"
        - name: STORAGE_PATH
          value: "./data/db"
        - name: OPERATOR_KEY
          value: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBb3pVaGFzSG9HeE1YS3pUbzgrSHdYZXR6cm1YQ1g5N215cGloeGMvbDFISWVJVXBXCmV3NkFNMzlPd1JQZ2VVMFZ3QmQ2NHZhbzZsTTNaQWxTdVZlMlpuU3RPTUlyQlNYZWxiRzRvUGtEbnFmQ01sYmYKa1RNRlhXVFowdE1IdGJwVkU3N2o0aEpxaUI3ZU13YitwNXUxWi82ZXFaNmZFZGc4MjkzM3dlSGFVY3N3ZklCaApYNlNaUjNlMkJvRUJ2bHljNE5ENEFoNVFaZjMrRWpxSit5dHZzeGJGbkw1SktZaGNKVzhia0J3M2gzZWt5RjJjCmI2eUE3M3dsTzZhWklaRWJ4QkE0WDl4WjhMSFBaNHJYWG9Gb2gxUUJ3UjE5RWF6YXlvSHVOYmRYakFtT2FzVWIKT0ttNFJBdk9ya1FwZ1I4S0J4NGMzczk0OFlidTBJRktQb0NIQndJREFRQUJBb0lCQUdGWXBXLzU3S21KZjM1RAo5dGJRNHdBQ0dtUGhTa2pJdVR3S1FpT3MxMWNhSWlLVkpuUUx1Q2YvUFVnb3hQRlZLeTRDVTBmZysrdVlheWQ5CjhCdWcxNmpRMnlsSmwwTmd6UnpZZmxsMWJkVktGcWpUN0ZHODd1dy81VFM4cnBLVWEzNTFrNU1halBSWUJRekcKbFVuL3Mvb3RneEdGRFRnbGxGZElWQ2tPdjV1YzlKMW9MVFQrMmV5Y1B1SHdDVlgxMkxZcXdmN2x1aDZ5UGZrYwp5UWFBOWMydW5NQWluaUZlbFNWWHpIZnpoWWFTZVhYdmVYcVU1NjYvVnJYU2MwNytFWG5oQktpZk95V01ZN0lZCitGNDAzdzF0TjVUeUVsTXdHMVhWbkI1MFljU3Y0WnFJVkE3aDVZVjR1aWZ2K3IxU0JJVFBHNlFzdWV2S0NNMHIKQkVVY0NpRUNnWUVBekFhdy9KOW1FQ1RZeVdFOWNkOE4rejFPdXBIVWZMcGxqVCtTOU1IbGFzWGlDdE04WXJtNAorZ2FGb3o0WHA0U2hqb1FCbThjZGdudW5HWitLakZkYlBDQlRZdi9sWjNBejUyTS9ZcWIvM1MwTXI1L2YxSStUCnBxUXRLUncyRTJuNG9Ma0hpWXFoUy9ySEY3VGRGR3dsSmlYYVJ2L09MN0RreFRrSklpcEdlVGtDZ1lFQXpNaUIKYml4L3Fua2VaYklsZEZwOFpDN1NoRFdTYkJvUHU1UEhnODdkbWFNSGhwTGQ1Z3M5T0RVc0lIbFAwN05vL21NQQpwZU9hREFMYS90R09DTVcvaEdaQW9vdEJFZnYrNW5FYndBSm52d1d3cVVoaFFBNkJocE5nODR0dGlnUlNxbFFrCmpmcHZCNmlZQ0k2ajRQVGhrWG1pM3hWc3VtM0JtMXBVUlpNb1FqOENnWUFEcXRNZmwxWGtVR1U5S1d4TFViRVUKcFFOM1F3dkl1aWo5SXZsblFOejQwRm5CekE0MzBCTE5HN1RuUEVSOGxGdTdEaEJoVm5EbldZV2xaa0s5Und5eQp4Zm41dTVQS0NqQkVwbm9MTWVsRGRuM1Y0ay9KcUZNRkdjcGVCTTNNQjRtYWlmaml0Z1UwTW12RnQxQ0ovMitqCmdlYXNoQWlXdnQwOTFrcWR2SmpMc1FLQmdHS2pKV3k2OUZkWmRhSElXREFlTVpKVDEwU2xSVHphcEw5V0pDREIKOEkxRE1LbktiaVdUUGs2bmxmU2lXaWYvWDlCQVFaeWw3NXBmZWJxSmwxOTBXSlplWmoyazA1ZmxDRmRaSGVPegpoT05HeTF3T3FBRWh1NVBsd3lvciszd2lMdXNxRWwxc3hqUXJLZWZkUk9Sakw0OVJ4bmlycWk1MkZXNU42UStHCkhUc2pBb0dBV0xYSmp6ZUREQVd0YnRSekRHTEY1ZXNYdjU5YU9McU1qMFhlTDJ2cmwxMjdka203ampJOTVDbWsKREZBOWx0cmhYRWZFcE9LUlBOTk54dnVQZUlWNlFRUXhRb1VFZFR4S0p3cENJQlBMK3U1MWlqNjlhZElQeXdNawprU2twaVJ4VEQvL1dQOGhseGlBM2FGYk05d0dSYlBudWtJdkFwd3RvUG5rV2RlYVRERk09Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg=="
        volumeMounts:
        - mountPath: /data
          name: ssv-node-v2-4
        - mountPath: /data/share.yaml
          subPath: share.yaml
          name: ssv-cm-validator-options-4
      volumes:
      - name: ssv-node-v2-4
        persistentVolumeClaim:
          claimName: ssv-node-v2-4
      - name: ssv-cm-validator-options-4
        configMap:
          name: ssv-cm-validator-options-4
      hostNetwork: true          
