---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-v2-3-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-v2-3
spec:
  type: ClusterIP
  ports:
    - port: 12000
      protocol: UDP
      targetPort: 12000
      name: port-12000
    - port: 13000
      protocol: TCP
      targetPort: 13000
      name: port-13000
  selector:
    app: ssv-node-v2-3
---
apiVersion: REPLACE_API_VERSION 
kind: Deployment
metadata:
  labels:
    app: ssv-node-v2-3
  name: ssv-node-v2-3
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-v2-3
  template:
    metadata:
      labels:
        app: ssv-node-v2-3
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - ssv-node-v2-1
              topologyKey: kubernetes.io/hostname
            weight: 1
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - ssv-node-v2-2
              topologyKey: kubernetes.io/hostname
            weight: 1
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - ssv-node-v2-4
              topologyKey: kubernetes.io/hostname
            weight: 1      
      containers:
      - name: ssv-node-v2-3
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG 
        imagePullPolicy: Always
        command: ["make", "start-node"]
        ports:
        - containerPort: 12000
          name: port-12000
          protocol: UDP
          hostPort: 12000            
        - containerPort: 13000
          name: port-13000
          hostPort: 13000
        env:
        - name: SHARE_CONFIG
          value: "./data/share.yaml"
        - name: NODE_ID
          value: "3"
        - name: SSV_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: ssv_node_v2_3
        - name: VALIDATOR_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: validator_public_key_v2
        - name: BEACON_NODE_ADDR
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: beacon_node_addr
        - name: PUBKEY_NODE_1
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: pubkey_node_v2_1
        - name: PUBKEY_NODE_2
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: pubkey_node_v2_2
        - name: PUBKEY_NODE_4
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: pubkey_node_v2_4
        - name: ETH_1_ADDR
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: eth1_addr
        - name: CONFIG_PATH
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: config_path
        - name: ENR_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: enr_key
        - name: SMART_CONTRACT_ADDR_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: smart_contract_addr_key
        - name: LOG_LEVEL
          value: "debug"
        - name: DISCOVERY_TYPE_KEY
          value: "discv5"
        - name: NETWORK
          value: "pyrmont" 
        - name: CONSENSUS_TYPE
          value: "validation"
        - name: HOST_DNS
          value: ""
        - name: HOST_ADDRESS
          value: ""
        - name: GENESIS_EPOCH
          value: "34165"
        - name: LOGGER_LEVEL
          value: "debug"
        - name: STORAGE_PATH
          value: "./data/db"
        - name: OPERATOR_KEY
          value: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBdVIzV0hmU1lhWlE0NjkxenR0aTZmUEFwTGprb0tzKytBL3RBZ1JVd0dsSFdibmI2CjJPVU4ra0tTUU53VWlNMFRwWGdOVHVSNGpjdWdKa1NTRlRSRHlYTC9JdGlvOUVkcTdoSFFDcERDTEJUU1hGU20KMjJrNlNRbllGeWs3UVNndnoyQW9mOXJ6YVdBQmVmUkZPdUs5cVZPTStvOGdGcXBxeVBGdElHL0JVL0VvWXYzQQpNU1A5UWJCTXRXSkIvcTd2QStZMUFrZEJiYUNuaGFkK1FUWGxjVWRLNFpsdnU1V0VaTEt0L04yVTVEZDBoWHhFCnBuRlo3L01SNVRnRVl2NFl3aUpHeWNyRTFKWGVSU2MrM21DWUp6RXNiMk9ZMFNkTzdiMExxZ2ozaFVrRG1wR1UKS2NoQlQyaGw0NWJ5ak4valZjUW1rb29lYUgzSCt2R2IvNzhVRXdJREFRQUJBb0lCQUJET2NxZ1prdFRURGkvcgoxUnVlcForK05oN3FOWWxkZndUaGhNT3pac0NjK1hqaCtIaEVvM1k3SVFnZWN3YlFoNTRZUGkwUmRSaDZpam12Ck5Bd1V5S3E3ZEFwMzNTOEFaT2JrV3h6NmM0YUpCV2c0ajBXUVVpaGJhbkQvMzA5VkZMSWhLc3dnMXNTVVlNM3YKclhGaE1KTDA4UEcybU5VMTk2ZnlzMU9ra2NyTERKTTU0RGQ2LzlBMm5LdmVYU3pCSjFBbGxGUCtpbUhFbCtQYQo3RUtxcUNKeGpxOUxLalRDV2pmTER5MXQ0YzE4eFgrRTBGTGdNUS9ybUVDS1VEazVCWHh3TE1mV1lQa3J0MkZTCnR6aVZVQXJCRHV4cEFZR2xBOXF6QVppRE0xaVJ1R3VPZnowNWpQUW5sUzF5SVFpQXRRUXJ2aE5MN245a3ZzSVEKeXcxc1AzRUNnWUVBeUV1TElKTis0NHpqYVBKY1BzN3RsRmFCMVNHMXAvblBoYkNSUkVDUGdEQnZ2QUdXbUZCQQpua2dnYTFTOFYyNk1SY1FTSk5PYUlrRHYrc2l4WWEybVo2N3ZTL3RUNEtRUWttSjBwdkptTHdVNUthMG04R00zCkNGRUR4T1BraHNTWEpHS3RiK2FpdXBHQ3JMZTdhWjZxLzE4K0toRk9VTVNYSytLaVFFY2gwSThDZ1lFQTdKbWYKWk1qMlJyNlhnQmhCUVp4c1AxZm4xdEUyNHRjVHYvbEhjVU82MTA4TnVLaXY2UkFZR3ZDM2VudUNtSjA2Si9IdQovakQxS20xVHpGUHJCZ2ZQczVmOVVWOW8xSXc0aEFnZ0hMcE4ya2svR2kvMFN3bG94Sm93OWJ3MldGTUZURnlDCldxaDY0WE9jM2dydUdlWDArY2d5RTV1UWttRnFtc1R5U2loV2ZqMENnWUJjNXgxTEtON01NUWN5SUdoRkFib1UKK2VNU3RxWUptY2QxM1NZa0lFWHZVWWdpRGlLSjEzK0JhemNPVWFsaWJIWkh6ZUFVa01tSFpkTnA0VGpWYzdRaApsM1NMSzdJR0dsTk5jcmxremo0elJScjBoOG50NmpjV2RtMW5IOFZaOVVtZHFOK0ZiZGJBN3NsTHo1VHdNcFppCkNRMU9lZVIzZGhnZ1ZPaXBJOVU5WlFLQmdHbFBEMFVhdFpOVGJiZFVGR2VScWhTZm1jOWhtNTVud0tDbjRZYW0KY05rNGxKRG1kRFcyTmlSM2xCTHVPbmlYTXJWbzE4bElIVGRmSmZkQ09zK2FWblpIWmpiNzBuc1lWbWRkL24wSwo1M0FMUGd6MzN6SXU0L1R0OUhETDd4eHRCMlN2b0UyZHcrUHBRNThKR21Wb2x4cytZaHVjR0VNdkhQWDZSeVYrCnd0QzVBb0dBSzQrNDFpZjlWb3JhL1N0OXRYbElmb2pXa1U5ZGN4aHdzdmErSXQ3UjAvTEFRT05Rb1hVUUZSbWkKM0VmNTE2Vmx3MFBUN1pxa0RkTVQyc1lkTVVkTGVHMVZtUVRlSXlzcWUwWmNFWUJYY3FwRXNVZEJkSzVjcytkVgoyYjMvYjh2KzY5aUMwVTRRaVU4TllGQ2pSWFdRck0rSmdnT0dCY3lxaTRpVjZkYm5mRU09Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg=="
        volumeMounts:
        - mountPath: /data
          name: ssv-node-v2-3
        - mountPath: /data/share.yaml
          subPath: share.yaml
          name: ssv-cm-validator-options-3
      volumes:
      - name: ssv-node-v2-3
        persistentVolumeClaim:
          claimName: ssv-node-v2-3
      - name: ssv-cm-validator-options-3
        configMap:
          name: ssv-cm-validator-options-3
      hostNetwork: true            
