version: '3.5'

x-base:
  &default-base
  build:
    context: .
    dockerfile: Dockerfile
  image: ssvnode:latest
  command: make BUILD_PATH=/go/bin/ssvnode start-node
  network_mode: host
#  networks:
#    - bloxapp-docker
  restart: always
  environment:
    CONFIG_PATH: ./config/config.yaml

x-base-dev:
  &default-dev
  << : *default-base
  image: ssvnode-debug:latest
  build:
    context: .
    dockerfile: dev.Dockerfile
  command:  air
  security_opt:
    - "seccomp:unconfined"
  cap_add:
    - SYS_PTRACE
  volumes:
    - ./:/go/src/github.com/bloxapp/ssv

services:
  ssv-node-1:
    <<: *default-base
    container_name: ssv-node-1
    environment:
      CONFIG_PATH: ./config/config.yaml
      SHARE_CONFIG: ./config/share1.yaml

  ssv-node-2:
    <<: *default-base
    container_name: ssv-node-2
    environment:
      CONFIG_PATH: ./config/config.yaml
      SHARE_CONFIG: ./config/share2.yaml

  ssv-node-3:
    <<: *default-base
    container_name: ssv-node-3
    environment:
      CONFIG_PATH: ./config/config.yaml
      SHARE_CONFIG: ./config/share3.yaml

  ssv-node-4:
    <<: *default-base
    container_name: ssv-node-4
    environment:
      CONFIG_PATH: ./config/config.yaml
      SHARE_CONFIG: ./config/share4.yaml


  ssv-node-1-dev:
    << : *default-dev
    container_name: ssv-node-1-dev
#    ports:
#      - 40005:40005
    environment:
      BUILD_PATH: /bin/tmp/ssv
      DEBUG_PORT: 40005
      CONFIG_PATH: ./config/config.yaml
      SHARE_CONFIG: ./config/share1.yaml

  ssv-node-2-dev:
    << : *default-dev
    container_name: ssv-node-2-dev
#    ports:
#      - 40006:40006
    environment:
      BUILD_PATH: /bin/tmp/ssv
      DEBUG_PORT: 40006
      CONFIG_PATH: ./config/config.yaml
      SHARE_CONFIG: ./config/share2.yaml

  ssv-node-3-dev:
    << : *default-dev
    container_name: ssv-node-3-dev
#    ports:
#      - 40007:40007
    environment:
      BUILD_PATH: /bin/tmp/ssv
      DEBUG_PORT: 40007
      CONFIG_PATH: ./config/config.yaml
      SHARE_CONFIG: ./config/share3.yaml

  ssv-node-4-dev:
    << : *default-dev
    container_name: ssv-node-4-dev
#    ports:
#      - 40008:40008
    environment:
      BUILD_PATH: /bin/tmp/ssv
      DEBUG_PORT: 40008
      CONFIG_PATH: ./config/config.yaml
      SHARE_CONFIG: ./config/share4.yaml

#networks:
#  bloxapp-docker:
#    driver: bridge
#    name: bloxapp-docker