db:
  Path: ./data/db/1
  Type: badger-db
ssv:
  ValidatorOptions:
    Shares:
      - NodeID: 1
        PublicKey: xxx-validator-pubkey
        ShareKey: xxx-share-privkey
        Committee: # <share-pub-key>: <node-id>
          share-pubkey-node1: 1
          share-pubkey-node2: 2
          share-pubkey-node3: 3
          share-pubkey-node4: 4